### ISSUE TITLE
Colorblind mode changes bg color

### ISSUE THREAD

**Issue by trevarj** [gbprod/nord.nvim#21]
Keep in mind, I'm not entirely sure how the colorblind mode _should_ work.

When colorblind mode is enabled, it may be best to not modify the background color, since this creates a difference in color with other nord themes, i.e terminal (if you have padding), tmux, window manager, etc.

Is it possible to have colorblind contrast but keep the original background color?

**Comment by Isrothy** [comment]
Currently there are two inelegant ways to solve this issue. One is to manually change all other nord themes, which is what I did. The other is manually change all background highlights in `on_highlight` function. Otherwise, new commits are needed to solve this issue.

I come up with two solutions. One is to add a new option here
``` lua
colorblind = {
    enable = false,
    preserve_background = false, -- Turn this on to preserve background.
    severity = {
      protan = 0.0,
      deutan = 0.0,
      tritan = 0.0,
    },
  }
```
Or to manually preserve polar_night.origin in a callback function

```lua
require("nord").setup({
    before_hightlight = function(palette) -- this function overrides color-blind mode
        palette.polar_night.origin = "#2E3440"
    end,
)}
```
@gbprod @trevarj What do you think?

**Comment by trevarj** [comment]
> One is to manually change all other nord themes, which is what I did

😩 

The `preserve_background` config seems pretty elegant to me. I will leave it up to the experts though!

**Comment by gbprod** [comment]
I agree with @trevarj , I prefer `preserve_background` solution.
I try to work on this soon

**Comment by gbprod** [comment]
I've made something here : #22
If you want to try before I merge

**Comment by trevarj** [comment]
@gbprod works as expected for me! thanks! 😄
